name: Check Commit Message Format

on:
  push:
    branches:
      - main

jobs:
  check_commit_message:
    runs-on: ubuntu-latest
    steps:
      - name: Check Commit Messages
        run: |
          for commit in $(git log --format="%H" HEAD~..HEAD); do
            message=$(git log --format="%s" -n 1 $commit)
            if ! echo "$message" | grep -Eq '^(feat|fix|docs|style|refactor|test|chore)(\(.+\))?: .{1,50}$'; then
              echo "Invalid commit message format: $message"
              exit 1
            fi
          done
